channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - spotiflow==0.5.2
      - fire==0.5.0
      - ome-zarr==0.8.0
      - ome-types==0.5.1
      - aicsimageio==4.14.0
      - dask-expr==0.2.9
      - shapely==2.0.3
      - numpy==1.24.4
