channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - fire==0.6.0
      - spatialdata==0.2.2
      - shapely==2.0.3
      - spatialdata-io==0.1.4
      - PyPika==0.48.9
      - numpy=2.1.0
      - psycopg2-binary==2.9.10
