channels:
  - conda-forge
dependencies:
  - numpy=1.24.4
  - pip
  - pip:
      - cucim==23.10.0
      - fire==0.5.0
      - ome-zarr==0.8.0
      - ome-types==0.5.1
      - aicsimageio==4.14.0
      - scipy==1.13.0
      - scikit-image==0.23.2
      - cupy-cuda110==12.3.0
